default:
  outputs:
    
    dev:
      type: bigquery
      method: service-account
      project: compact-arc-447521-f9
      dataset: dbt_staging
      location: us-west1
      keyfile: /secrets/creds.json
    
    semi:
      type: bigquery
      method: service-account
      project: compact-arc-447521-f9
      dataset: semi_processed
      location: us-west1
      keyfile: /secrets/creds.json

    final:
      type: bigquery
      method: service-account
      project: compact-arc-447521-f9
      dataset: final_transformed
      location: us-west1
      keyfile: /secrets/creds.json
  
  target: dev