version: '3.9'

services:
  kestra:
    build: ./docker/kestra
    container_name: kestra
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}  # Mount GCP credentials
      - ./docker/kestra/application.yaml:/app/config/application.yaml  # Custom config
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    networks:
      - lewis-hamilton

  spark:
    build: ./docker/spark
    container_name: spark
    volumes:
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      SPARK_MODE: master
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - "7077:7077"
      - "8081:8081"
    networks:
      - lewis-hamilton

  spark-worker-1:
    build: ./docker/spark
    container_name: spark-worker-1
    volumes:
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      LD_PRELOAD: ""
    depends_on:
      - spark
    networks:
      - lewis-hamilton

  spark-worker-2:
    build: ./docker/spark
    container_name: spark-worker-2
    volumes:
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      LD_PRELOAD: ""
    depends_on:
      - spark
    networks:
      - lewis-hamilton

  spark-worker-3:
    build: ./docker/spark
    container_name: spark-worker-3
    volumes:
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      LD_PRELOAD: ""
    depends_on:
      - spark
    networks:
      - lewis-hamilton

  dbt:
    build: ./docker/dbt
    container_name: dbt
    volumes:
      - ./dbt:/app/dbt
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      DBT_PROFILES_DIR: /app/dbt
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]
    working_dir: /app/dbt
    depends_on:
      - spark
    networks:
      - lewis-hamilton

  terraform:
    build: ./docker/terraform
    container_name: terraform
    volumes:
      - ./terraform:/terraform
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    working_dir: /terraform
    entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]
    networks:
      - lewis-hamilton

  gcloud:
    image: google/cloud-sdk:slim
    container_name: gcloud
    volumes:
      - ./scripts:/scripts
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    entrypoint: ["/bin/sh", "-c", "gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS} && while true; do sleep 30; done"]
    networks:
      - lewis-hamilton

  ingestion:
    build:
      context: .
      dockerfile: docker/ingestion/Dockerfile
    container_name: ingestion
    volumes:
      - ./ingestion:/app/ingestion
      - ./data/raw:/app/data/raw
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      F1DB_RELEASE_URL: ${F1DB_RELEASE_URL}
      RAW_DATA_DIR: ${RAW_DATA_DIR}
      GCS_BUCKET: ${GCS_BUCKET}
      GCS_PREFIX: ${GCS_PREFIX}
    entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]
    networks:
      - lewis-hamilton

networks:
  lewis-hamilton:
    driver: bridge

  # looker:
  #   image: looker/looker
  #   container_name: looker
  #   ports:
  #     - "9999:9999"
  #   environment:
  #     LOOKER_PORT: 9999
  #   depends_on:
  #     - dbt
