version: '3.9'

services:
  kestra:
    build: ./docker/kestra
    container_name: kestra
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
      - ${PWD}/docker/kestra/application.yaml:/app/config/application.yaml
      - ${PWD}/dags:/app/dags
    command: server standalone
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      KESTRA_CONFIGURATION_PATH: /app/config/application.yaml
    networks:
      - lewis-hamilton
  kestra-cli:
    image: kestra/kestra:latest
    platform: linux/amd64
    pull_policy: always
    container_name: kestra-cli
    entrypoint: ["/bin/sh", "-c"]
    command: ["while true; do sleep 3600; done"]
    volumes:
      # - ${PWD}/dags:/app/dags
      - .:/workspace
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    networks:
      - lewis-hamilton

    #     kestra-cli:
    # image: kestra/kestra:latest
    # platform: linux/arm64
    # pull_policy: always
    # container_name: kestra-cli
    # entrypoint: ["/app/kestra"]
    # command: server standalone
    # volumes:
    #   - ${PWD}:/workspace
    #   - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    # environment:
    #   GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    # networks:
    #   - lewis-hamilton


  spark:
    build: ./docker/spark
    container_name: spark
    volumes:
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      SPARK_MODE: master
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - "7077:7077"
      - "8081:8081"
    networks:
      - lewis-hamilton

  spark-worker-1:
    build: ./docker/spark
    container_name: spark-worker-1
    volumes:
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      LD_PRELOAD: ""
    depends_on:
      - spark
    networks:
      - lewis-hamilton

  spark-worker-2:
    build: ./docker/spark
    container_name: spark-worker-2
    volumes:
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      LD_PRELOAD: ""
    depends_on:
      - spark
    networks:
      - lewis-hamilton

  spark-worker-3:
    build: ./docker/spark
    container_name: spark-worker-3
    volumes:
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      LD_PRELOAD: ""
    depends_on:
      - spark
    networks:
      - lewis-hamilton

  dbt:
    build: ./docker/dbt
    container_name: dbt
    volumes:
      - ./dbt:/app/dbt
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      DBT_PROFILES_DIR: /app/dbt
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]
    working_dir: /app/dbt
    depends_on:
      - spark
    networks:
      - lewis-hamilton

  terraform:
    build: ./docker/terraform
    container_name: terraform
    volumes:
      - ./terraform:/terraform
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    working_dir: /terraform
    entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]
    networks:
      - lewis-hamilton

  gcloud:
    image: google/cloud-sdk:slim
    container_name: gcloud
    volumes:
      - ./scripts:/scripts
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    entrypoint: ["/bin/sh", "-c", "gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS} && while true; do sleep 30; done"]
    networks:
      - lewis-hamilton

  ingestion:
    build:
      context: .
      dockerfile: docker/ingestion/Dockerfile
    container_name: ingestion
    volumes:
      - ./ingestion:/app/ingestion
      - ./data/raw:/app/data/raw
      - ${GOOGLE_CREDENTIALS_HOST}:${GOOGLE_APPLICATION_CREDENTIALS}
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      F1DB_RELEASE_URL: ${F1DB_RELEASE_URL}
      RAW_DATA_DIR: ${RAW_DATA_DIR}
      GCS_BUCKET: ${GCS_BUCKET}
      GCS_PREFIX: ${GCS_PREFIX}
    entrypoint: ["/bin/sh", "-c", "tail -f /dev/null"]
    networks:
      - lewis-hamilton

networks:
  lewis-hamilton:
    driver: bridge
