default:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: compact-arc-447521-f9
      dataset: dbt_staging
      keyfile: /root/.google/credentials/google_credentials.json
  target: dev